name: Test Workflow

on:
  push:
    branches:
      - Main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello World
        run: echo "Workflow is working!"
